name: CLI Ubuntu Runner

on:  
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
  trigger_pipeline:
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
        
      - name: Docker Pull postgres
        run: docker pull postgres

      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations
          image: postgres
          ignore-unchanged: true
          only-severities: critical,high,medium,low
          only-fixed: false

      
      - name: Install Puppeteer
        run: |
          sudo apt update
          sudo apt install -y nodejs npm
          npm install puppeteer

      - name: Generate PDF
        run: |
          node generate_pdf.js

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-scout-report
          path: docker_scout_report.pdf
          sarif-file: sarif.output.json
          summary: true



