name: ZAP Scan Filter
on:
  push:
    branches: [Testing]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up ZAP Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          target: 'http://www.itsecgames.com/'
          format: 'json'
          report: 'zap_report.zip'

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Extract the ZIP report
        run: |
          mkdir zap_report
          unzip zap_report.zip -d zap_report

      - name: Filter Medium and High Defects (exclude Low)
        run: |
          jq '{
            site: [
              {
                alerts: [
                  .site[].alerts[] | select(.risk == "Medium" or .risk == "High")
                ]
              }
            ]
          }' zap_report/zap_report.json > zap_report/filtered_zap_report.json

      - name: Re-zip the Filtered Report
        run: |
          cd zap_report
          zip -r filtered_zap_report.zip filtered_zap_report.json

      - name: Upload Filtered ZIP Report
        uses: actions/upload-artifact@v3
        with:
          name: filtered_zap_scan
          path: zap_report/filtered_zap_report.zip
